namespace = "inference"
dependencies = ["functional"]


[[handlers]]
name = "inferfn"
subsystem = "functional"
path = "inference::InferFn"
mem = 768
timeout = 30
scaleup = 0.5
ephemeral = 4096
concurrency = 1


[[handlers]]
name = "benchfn"
subsystem = "functional"
path = "inference::BenchFn"
mem = 512
timeout = 30
scaleup = -1.0
concurrency = 16
